### PR TITLE
Remove no longer necessary MacOS RUSTFLAGS hack

### PR DESCRIPTION
**Pull request by lrascao**
The two PRs mentioned in the comments have since been merged, this can now be dropped.

### CODE REVIEW

**Comment by filmor** [comment]
The "hack" is still necessary, AFAICT, nothing changed in regard to this. The only thing that changed is that people are working on improving the syntax. The comments are probably outdated, though.

**Comment by lrascao** [comment]
I noticed this when i bumped rust to 1.49, linking started failing on our tests at `rebar3_cargo`. Not too sure on the exact root cause for the failure but this is the way i found of going around it.

**Comment by belltoy** [comment]
Hi, guys. Since https://github.com/rust-lang/rust/pull/36574 had been merged, the hack was also outdated. We still need to specify RUSTFLAGS for different targets, but it can be done via `.cargo/config.toml` instead of hard-coded hack like that. e.g:

```toml
# .cargo/config.toml
[target.'cfg(target_os = "macos")']
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]
```

So, this PR can be merged IMO.

**Comment by belltoy** [comment]
According to  https://github.com/rusterlium/rustler/pull/192 and the [Apple reference](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/MachOTopics/1-Articles/executing_files.html), the _two-level namespace_ is preferred, and:

> When building executables with a two-level namespace, you can allow the remaining undefined symbols to be looked up by the dynamic linker if the program is targeted for OS X v10.3 and later (the `MACOSX_DEPLOYMENT_TARGET` environment variable is set to 10.3 or higher). To take advantage of this feature, use the `-undefined dynamic_lookup` option.

So with two-level namespace args in my example lib:

```
$ otool -hV priv/crates/my_nif/0.1.0/debug/libmy_nif.so
priv/crates/my_nif/0.1.0/debug/libmy_nif.so:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   X86_64        ALL  0x00       DYLIB    16       2064   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS MH_HAS_TLV_DESCRIPTORS
```

Meanwhile, the preferred for rust/cargo is to put RUSTFLAGS in the cargo config file.

@filmor cc @lrascao

**Review by filmor — APPROVED** [review]

**Comment by lrascao** [comment]
i'll take care of the merge conflict

**Comment by belltoy** [comment]
Great! And should bump a new version to fix https://github.com/rusterlium/rebar3_cargo/pull/6 which may should be update to using the new fix with a cargo config file?

**Comment by belltoy** [comment]
@filmor Could you bump a new release? And have a review at https://github.com/rusterlium/rebar3_cargo/pull/8 if you have time. 🙂

**Pull request merged**
