### PR TITLE
Expose `target-dir` cargo build option

### PR DESCRIPTION
**Pull request by lrascao**

### CODE REVIEW

**Comment by filmor** [comment]
What's the rationale behind this? I don't have anything against this (I think), I just wonder when it would be useful.

**Comment by lrascao** [comment]
It's being used in the open rebar3_cargo PR to generate rust's 'target' in rebar3's _build dir alongside the other artifacts

**Comment by filmor** [comment]
The idea was that (modulo copying to `priv`) compiling via `cargo build` on the command line does the same thing as compiling via `rebar3_cargo`.

**Comment by lrascao** [comment]
What i got was that this component is a simple erlang wrapper over `cargo` that the `rebar3_cargo` plugin is a client of. `rebar3` generates all it's artifacts to `_build` and it stands to reason that the plugins should as well. I suppose we can open up an option in the plugin to keep the previous target dir by default (althout imo people aren't really expecting that)

**Comment by filmor** [comment]
This is indeed supposed to be a wrapper around `cargo`, including processing of the JSON formatted messages, and `rebar3_cargo` uses it to run the actual builds and capture the artifacts, which are then copied to the appropriate location.

`rebar3`'s [default Makefile](https://github.com/erlang/rebar3/blob/master/priv/templates/Makefile) also builds the object files in-place in the `c_src` directory and only outputs the linked result to the `priv`, not even that one is going directly to `_build`.

**Comment by filmor** [comment]
Just to be clear, I'm fine with the feature in here (and the clean-ups), whether `rebar3_cargo` should by default use it is a different story.

**Comment by lrascao** [comment]
@filmor Maybe we can take guidance from the (port compiler)[https://www.rebar3.org/docs/using-available-plugins#port-compiler] plugin mentioned in the docs that's used in jiffy, I'll take a look and check how it handles the target locations and go from there

**Pull request merged**
